# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Carl Gustafson
tagline:          'medical scientist, question artist, dilettante'
description:      'Carl Gustafson'
url:              http://carlgustafson.org

author:
  name:           'Carl Gustafson'
  url:            https://twitter.com/carlgus1



# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/carlgus/carlgus.github.io/
